routes:
  sho19:
    name: 湘19
    paths:
      sho19_to:
        name: 綾瀬車庫行
        origin: 湘南台駅西口
        destination: 綾瀬車庫
        via: 慶応大学・宮原
        sfc_direction: to
        stops:
          - name: 湘南台駅西口
            cumulative_time: 0
          - name: 円行上庭
            cumulative_time: 1
          - name: 北警察署前
            cumulative_time: 2
          - name: 工業団地入口
            cumulative_time: 4
          - name: 南大山
            cumulative_time: 5
          - name: 遠藤
            cumulative_time: 7
          - name: 藤沢ジャンボゴルフ前
            cumulative_time: 8
          - name: 慶応大学
            cumulative_time: 11
        csv_files:
          weekday: csv/sho19_to_weekday.csv
          saturday: csv/sho19_to_saturday.csv
          sunday: csv/sho19_to_sunday.csv
      sho19_from:
        name: 湘南台駅西口行
        origin: 慶応大学
        destination: 湘南台駅西口
        via: 宮原・慶応大学
        sfc_direction: from
        stops:
          - name: 慶応大学
            cumulative_time: 0
          - name: 藤沢ジャンボゴルフ前
            cumulative_time: 1
          - name: 遠藤
            cumulative_time: 2
          - name: 南大山
            cumulative_time: 4
          - name: 工業団地入口
            cumulative_time: 5
          - name: 北警察署前
            cumulative_time: 6
          - name: 湘南台駅西口
            cumulative_time: 12
        csv_files:
          weekday: csv/sho19_from_weekday.csv
          saturday: csv/sho19_from_saturday.csv
          sunday: csv/sho19_from_sunday.csv
  sho23:
    name: 湘23
    paths:
      sho23_to:
        name: 慶応中高等部前行
        origin: 湘南台駅西口
        destination: 慶応中高等部前
        via: 遠藤
        sfc_direction: to
        stops:
          - name: 湘南台駅西口
            cumulative_time: 0
          - name: 円行上庭
            cumulative_time: 1
          - name: 北警察署前
            cumulative_time: 2
          - name: 工業団地入口
            cumulative_time: 4
          - name: 南大山
            cumulative_time: 5
          - name: 遠藤
            cumulative_time: 7
          - name: 藤沢ジャンボゴルフ前
            cumulative_time: 8
          - name: 慶応大学
            cumulative_time: 11
          - name: 慶応大学本館前
            cumulative_time: 12
          - name: 慶応中高等部前
            cumulative_time: 15
        csv_files:
          weekday: csv/sho23_to_weekday.csv
          saturday: csv/sho23_to_saturday.csv
      sho23_to_sun:
        name: 慶応大学行
        origin: 湘南台駅西口
        destination: 慶応大学
        via: 遠藤
        sfc_direction: to
        stops:
          - name: 湘南台駅西口
            cumulative_time: 0
          - name: 円行上庭
            cumulative_time: 1
          - name: 北警察署前
            cumulative_time: 2
          - name: 工業団地入口
            cumulative_time: 4
          - name: 南大山
            cumulative_time: 5
          - name: 遠藤
            cumulative_time: 7
          - name: 藤沢ジャンボゴルフ前
            cumulative_time: 8
          - name: 慶応大学
            cumulative_time: 11
        csv_files:
          sunday: csv/sho23_to_sun_sunday.csv
      sho23_from_honkan:
        name: 湘南台駅西口行
        origin: 慶応大学本館前
        destination: 湘南台駅西口
        via: 遠藤
        sfc_direction: from
        stops:
          - name: 慶応大学本館前
            cumulative_time: 0
          - name: 慶応大学
            cumulative_time: 1
          - name: 藤沢ジャンボゴルフ前
            cumulative_time: 2
          - name: 遠藤
            cumulative_time: 3
          - name: 南大山
            cumulative_time: 5
          - name: 工業団地入口
            cumulative_time: 6
          - name: 北警察署前
            cumulative_time: 7
          - name: 湘南台駅西口
            cumulative_time: 13
        csv_files:
          weekday: csv/sho23_from_honkan_weekday.csv
          saturday: csv/sho23_from_honkan_saturday.csv
      sho23_from_rotary:
        name: 湘南台駅西口行
        origin: 慶応大学
        destination: 湘南台駅西口
        via: 遠藤
        sfc_direction: from
        stops:
          - name: 慶応大学
            cumulative_time: 0
          - name: 藤沢ジャンボゴルフ前
            cumulative_time: 1
          - name: 遠藤
            cumulative_time: 2
          - name: 南大山
            cumulative_time: 4
          - name: 工業団地入口
            cumulative_time: 5
          - name: 北警察署前
            cumulative_time: 6
          - name: 湘南台駅西口
            cumulative_time: 11
        csv_files:
          weekday: csv/sho23_from_rotary_weekday.csv
          saturday: csv/sho23_from_rotary_saturday.csv
          sunday: csv/sho23_from_rotary_sunday.csv
  sho24:
    name: 湘24
    paths:
      sho24_to:
        name: 慶応中高等部前行
        origin: 湘南台駅西口
        destination: 慶応中高等部前
        via: 遠藤・笹久保
        sfc_direction: to
        stops:
          - name: 湘南台駅西口
            cumulative_time: 0
          - name: 円行上庭
            cumulative_time: 1
          - name: 北警察署前
            cumulative_time: 2
          - name: 工業団地入口
            cumulative_time: 4
          - name: 南大山
            cumulative_time: 5
          - name: 遠藤
            cumulative_time: 7
          - name: 六地蔵
            cumulative_time: 9
          - name: 仲之桜
            cumulative_time: 10
          - name: 笹久保
            cumulative_time: 11
          - name: 慶応大学
            cumulative_time: 13
          - name: 慶応大学本館前
            cumulative_time: 14
          - name: 慶応中高等部前
            cumulative_time: 16
        csv_files:
          weekday: csv/sho24_to_weekday.csv
      sho24_from:
        name: 湘南台駅西口行
        origin: 慶応大学
        destination: 湘南台駅西口
        via: 笹久保・遠藤
        sfc_direction: from
        stops:
          - name: 慶応大学
            cumulative_time: 0
          - name: 笹久保
            cumulative_time: 2
          - name: 仲之桜
            cumulative_time: 3
          - name: 六地蔵
            cumulative_time: 4
          - name: 遠藤
            cumulative_time: 5
          - name: 南大山
            cumulative_time: 7
          - name: 工業団地入口
            cumulative_time: 8
          - name: 北警察署前
            cumulative_time: 9
          - name: 湘南台駅西口
            cumulative_time: 15
        csv_files:
          weekday: csv/sho24_from_weekday.csv
  sho25:
    name: 湘25
    paths:
      sho25_to:
        name: ツインライナー 急行・慶応大学行
        origin: 湘南台駅西口
        destination: 慶応中高等部前
        via: ツインライナー急行・南大山
        sfc_direction: to
        stops:
          - name: 湘南台駅西口
            cumulative_time: 0
          - name: 南大山
            cumulative_time: 5
          - name: 慶応大学
            cumulative_time: 9
          - name: 慶応大学本館前
            cumulative_time: 12
          - name: 慶応中高等部前
            cumulative_time: 15
        csv_files:
          weekday: csv/sho25_to_weekday.csv
          saturday: csv/sho25_to_saturday.csv
      sho25_from_honkan:
        name: ツインライナー 急行・湘南台駅西口行
        origin: 慶応大学本館前
        destination: 湘南台駅西口
        via: ツインライナー急行・南大山
        sfc_direction: from
        stops:
          - name: 慶応大学本館前
            cumulative_time: 0
          - name: 慶応大学
            cumulative_time: 1
          - name: 南大山
            cumulative_time: 5
          - name: 湘南台駅西口
            cumulative_time: 16
        csv_files:
          weekday: csv/sho25_from_honkan_weekday.csv
          saturday: csv/sho25_from_honkan_saturday.csv
      sho25_from_rotary:
        name: ツインライナー 急行・湘南台駅西口行
        origin: 慶応大学
        destination: 湘南台駅西口
        via: ツインライナー急行・南大山
        sfc_direction: from
        stops:
          - name: 慶応大学
            cumulative_time: 0
          - name: 南大山
            cumulative_time: 4
          - name: 湘南台駅西口
            cumulative_time: 13
        csv_files:
          weekday: csv/sho25_from_rotary_weekday.csv
          saturday: csv/sho25_from_rotary_saturday.csv
  sho28:
    name: 湘28
    paths:
      sho28_to:
        name: 直行 慶応中高等部前行
        origin: 湘南台駅西口
        destination: 慶応中高等部前
        via: 直行
        sfc_direction: to
        stops:
          - name: 湘南台駅西口
            cumulative_time: 0
          - name: 慶応中高等部前
            cumulative_time: 13
        csv_files:
          weekday: csv/sho28_to_weekday.csv
          saturday: csv/sho28_to_saturday.csv
      sho28_from:
        name: 直行 湘南台駅西口行
        origin: 慶応大学本館前
        destination: 湘南台駅西口
        via: 直行
        sfc_direction: from
        stops:
          - name: 慶応大学本館前
            cumulative_time: 0
          - name: 湘南台駅西口
            cumulative_time: 13
        csv_files:
          weekday: csv/sho28_from_weekday.csv
  tsuji34:
    name: 辻34
    station: tsujido
    paths:
      tsuji34_to:
        name: 慶応中高降車場行
        origin: 辻堂駅北口
        destination: 慶応中高降車場
        via: 大庭隧道・駒寄
        sfc_direction: to
        stops:
          - name: 辻堂駅北口
            cumulative_time: 0
          - name: 神台公園前
            cumulative_time: 1
          - name: 羽鳥一丁目
            cumulative_time: 2
          - name: 城南一丁目
            cumulative_time: 3
          - name: 大庭隧道
            cumulative_time: 4
          - name: 有藤
            cumulative_time: 5
          - name: 西高校前
            cumulative_time: 6
          - name: 南センター前
            cumulative_time: 7
          - name: 小糸
            cumulative_time: 8
          - name: 大庭小学校
            cumulative_time: 9
          - name: ライフタウン中央
            cumulative_time: 10
          - name: 二番構保健医療センター
            cumulative_time: 11
          - name: 駒寄
            cumulative_time: 12
          - name: 滝の沢（藤沢市）
            cumulative_time: 13
          - name: 滝の沢不動前
            cumulative_time: 14
          - name: 湘南ライフタウン
            cumulative_time: 15
          - name: 刈込
            cumulative_time: 18
          - name: 諸之木
            cumulative_time: 19
          - name: 慶応大学
            cumulative_time: 20
          - name: 慶応大学本館前
            cumulative_time: 21
          - name: 慶応中高降車場
            cumulative_time: 25
        csv_files:
          weekday: csv/tsuji34_to_weekday.csv
          saturday: csv/tsuji34_to_saturday.csv
      tsuji34_to_sun:
        name: 慶応大学行
        origin: 辻堂駅北口
        destination: 慶応大学
        via: 大庭隧道・駒寄
        sfc_direction: to
        stops:
          - name: 辻堂駅北口
            cumulative_time: 0
          - name: 神台公園前
            cumulative_time: 1
          - name: 羽鳥一丁目
            cumulative_time: 2
          - name: 城南一丁目
            cumulative_time: 3
          - name: 大庭隧道
            cumulative_time: 4
          - name: 有藤
            cumulative_time: 5
          - name: 西高校前
            cumulative_time: 6
          - name: 南センター前
            cumulative_time: 7
          - name: 小糸
            cumulative_time: 8
          - name: 大庭小学校
            cumulative_time: 9
          - name: ライフタウン中央
            cumulative_time: 10
          - name: 二番構保健医療センター
            cumulative_time: 11
          - name: 駒寄
            cumulative_time: 12
          - name: 滝の沢（藤沢市）
            cumulative_time: 13
          - name: 滝の沢不動前
            cumulative_time: 14
          - name: 湘南ライフタウン
            cumulative_time: 15
          - name: 刈込
            cumulative_time: 18
          - name: 諸之木
            cumulative_time: 19
          - name: 慶応大学
            cumulative_time: 24
        csv_files:
          sunday: csv/tsuji34_to_sun_sunday.csv
      tsuji34_from_honkan:
        name: 辻堂駅北口行
        origin: 慶応大学本館前
        destination: 辻堂駅北口
        via: 駒寄・大庭隧道
        sfc_direction: from
        stops:
          - name: 慶応大学本館前
            cumulative_time: 0
          - name: 慶応大学
            cumulative_time: 1
          - name: 諸之木
            cumulative_time: 2
          - name: 刈込
            cumulative_time: 3
          - name: 湘南ライフタウン
            cumulative_time: 8
          - name: 滝の沢不動前
            cumulative_time: 9
          - name: 滝の沢（藤沢市）
            cumulative_time: 10
          - name: 駒寄
            cumulative_time: 11
          - name: 二番構保健医療センター
            cumulative_time: 12
          - name: ライフタウン中央
            cumulative_time: 13
          - name: 大庭小学校
            cumulative_time: 14
          - name: 小糸
            cumulative_time: 15
          - name: 南センター前
            cumulative_time: 16
          - name: 西高校前
            cumulative_time: 17
          - name: 有藤
            cumulative_time: 18
          - name: 大庭隧道
            cumulative_time: 19
          - name: 城南一丁目
            cumulative_time: 20
          - name: 羽鳥一丁目
            cumulative_time: 21
          - name: 神台公園前
            cumulative_time: 21
          - name: 辻堂駅北口
            cumulative_time: 26
        csv_files:
          weekday: csv/tsuji34_from_honkan_weekday.csv
      tsuji34_from_honkan_weekend:
        name: 辻堂駅北口行
        origin: 慶応大学本館前
        destination: 辻堂駅北口
        via: 駒寄・大庭隧道
        sfc_direction: from
        stops:
          - name: 慶応大学本館前
            cumulative_time: 0
          - name: 慶応大学
            cumulative_time: 1
          - name: 諸之木
            cumulative_time: 2
          - name: 刈込
            cumulative_time: 3
          - name: 湘南ライフタウン
            cumulative_time: 8
          - name: 滝の沢不動前
            cumulative_time: 9
          - name: 滝の沢（藤沢市）
            cumulative_time: 10
          - name: 駒寄
            cumulative_time: 11
          - name: 二番構保健医療センター
            cumulative_time: 12
          - name: ライフタウン中央
            cumulative_time: 13
          - name: 大庭小学校
            cumulative_time: 14
          - name: 小糸
            cumulative_time: 15
          - name: 南センター前
            cumulative_time: 16
          - name: 西高校前
            cumulative_time: 17
          - name: 有藤
            cumulative_time: 18
          - name: 大庭隧道
            cumulative_time: 19
          - name: 城南一丁目
            cumulative_time: 20
          - name: 神台公園前
            cumulative_time: 22
          - name: 辻堂駅北口
            cumulative_time: 25
        csv_files:
          saturday: csv/tsuji34_from_honkan_weekend_saturday.csv
      tsuji34_from_rotary:
        name: 辻堂駅北口行
        origin: 慶応大学
        destination: 辻堂駅北口
        via: 駒寄・大庭隧道
        sfc_direction: from
        stops:
          - name: 慶応大学
            cumulative_time: 0
          - name: 諸之木
            cumulative_time: 1
          - name: 刈込
            cumulative_time: 2
          - name: 湘南ライフタウン
            cumulative_time: 7
          - name: 滝の沢不動前
            cumulative_time: 8
          - name: 滝の沢（藤沢市）
            cumulative_time: 9
          - name: 駒寄
            cumulative_time: 10
          - name: 二番構保健医療センター
            cumulative_time: 11
          - name: ライフタウン中央
            cumulative_time: 12
          - name: 大庭小学校
            cumulative_time: 13
          - name: 小糸
            cumulative_time: 14
          - name: 南センター前
            cumulative_time: 15
          - name: 西高校前
            cumulative_time: 16
          - name: 有藤
            cumulative_time: 17
          - name: 大庭隧道
            cumulative_time: 18
          - name: 城南一丁目
            cumulative_time: 19
          - name: 羽鳥一丁目
            cumulative_time: 20
          - name: 神台公園前
            cumulative_time: 21
          - name: 辻堂駅北口
            cumulative_time: 24
        csv_files:
          weekday: csv/tsuji34_from_rotary_weekday.csv
      tsuji34_from_rotary_weekend:
        name: 辻堂駅北口行
        origin: 慶応大学
        destination: 辻堂駅北口
        via: 駒寄・大庭隧道
        sfc_direction: from
        stops:
          - name: 慶応大学
            cumulative_time: 0
          - name: 諸之木
            cumulative_time: 1
          - name: 刈込
            cumulative_time: 2
          - name: 湘南ライフタウン
            cumulative_time: 7
          - name: 滝の沢不動前
            cumulative_time: 8
          - name: 滝の沢（藤沢市）
            cumulative_time: 9
          - name: 駒寄
            cumulative_time: 10
          - name: 二番構保健医療センター
            cumulative_time: 11
          - name: ライフタウン中央
            cumulative_time: 12
          - name: 大庭小学校
            cumulative_time: 13
          - name: 小糸
            cumulative_time: 14
          - name: 南センター前
            cumulative_time: 15
          - name: 西高校前
            cumulative_time: 16
          - name: 有藤
            cumulative_time: 17
          - name: 大庭隧道
            cumulative_time: 18
          - name: 城南一丁目
            cumulative_time: 19
          - name: 神台公園前
            cumulative_time: 21
          - name: 辻堂駅北口
            cumulative_time: 24
        csv_files:
          saturday: csv/tsuji34_from_rotary_weekend_saturday.csv
          sunday: csv/tsuji34_from_rotary_weekend_sunday.csv
  tsuji35:
    name: 辻35
    station: tsujido
    paths:
      tsuji35_to:
        name: ツインライナー 急行・慶応中高降車場行
        origin: 辻堂駅北口
        destination: 慶応中高降車場
        via: ツインライナー急行・駒寄
        sfc_direction: to
        stops:
          - name: 辻堂駅北口
            cumulative_time: 0
          - name: 西高校前
            cumulative_time: 6
          - name: 小糸
            cumulative_time: 8
          - name: ライフタウン中央
            cumulative_time: 10
          - name: 二番構保健医療センター
            cumulative_time: 11
          - name: 駒寄
            cumulative_time: 12
          - name: 滝の沢（藤沢市）
            cumulative_time: 13
          - name: 滝の沢不動前
            cumulative_time: 14
          - name: 湘南ライフタウン
            cumulative_time: 15
          - name: 刈込
            cumulative_time: 18
          - name: 諸之木
            cumulative_time: 19
          - name: 慶応大学
            cumulative_time: 20
          - name: 慶応大学本館前
            cumulative_time: 21
          - name: 慶応中高降車場
            cumulative_time: 25
        csv_files:
          weekday: csv/tsuji35_to_weekday.csv
      tsuji35_from_honkan:
        name: ツインライナー 急行・辻堂駅北口行
        origin: 慶応大学本館前
        destination: 辻堂駅北口
        via: ツインライナー急行・駒寄
        sfc_direction: from
        stops:
          - name: 慶応大学本館前
            cumulative_time: 0
          - name: 慶応大学
            cumulative_time: 1
          - name: 諸之木
            cumulative_time: 2
          - name: 刈込
            cumulative_time: 3
          - name: 湘南ライフタウン
            cumulative_time: 8
          - name: 滝の沢不動前
            cumulative_time: 9
          - name: 滝の沢（藤沢市）
            cumulative_time: 10
          - name: 駒寄
            cumulative_time: 11
          - name: 二番構保健医療センター
            cumulative_time: 12
          - name: ライフタウン中央
            cumulative_time: 13
          - name: 小糸
            cumulative_time: 15
          - name: 辻堂駅北口
            cumulative_time: 26
        csv_files:
          weekday: csv/tsuji35_from_honkan_weekday.csv
      tsuji35_from_rotary:
        name: ツインライナー 急行・辻堂駅北口行
        origin: 慶応大学
        destination: 辻堂駅北口
        via: ツインライナー急行・駒寄
        sfc_direction: from
        stops:
          - name: 慶応大学
            cumulative_time: 0
          - name: 諸之木
            cumulative_time: 1
          - name: 刈込
            cumulative_time: 2
          - name: 湘南ライフタウン
            cumulative_time: 7
          - name: 滝の沢不動前
            cumulative_time: 8
          - name: 滝の沢（藤沢市）
            cumulative_time: 9
          - name: 駒寄
            cumulative_time: 10
          - name: 二番構保健医療センター
            cumulative_time: 11
          - name: ライフタウン中央
            cumulative_time: 12
          - name: 小糸
            cumulative_time: 14
          - name: 辻堂駅北口
            cumulative_time: 24
        csv_files:
          weekday: csv/tsuji35_from_rotary_weekday.csv
