special_schedules:
  - date: "2025-07-05"
    description: "慶応大学藤沢湘南キャンパス「七夕祭」開催に伴う臨時便の運行および起終点の変更"
    type: "special_20250705"
    overrides: # この日に上書きされる路線とCSVファイル
      sho23:
        sho23_to: "csv/special/20250705_sho23_to.csv"
        sho23_from_rotary: "csv/special/20250705_sho23_from_rotary.csv"
      sho25:
        sho25_to: "csv/special/20250705_sho25_to.csv"
        sho23_from_rotary: "csv/special/20250705_sho23_from_rotary.csv"
