special_schedules:
  - date: "2025-07-05"
    description: "慶応大学藤沢湘南キャンパス「七夕祭」開催に伴う臨時便の運行および起終点の変更"
    type: "special_20250705"
    routes:
      sho23:
        name: 湘23
        paths:
          sho23_to:
            name: 慶応中高等部前行
            origin: 湘南台駅西口
            destination: 慶応中高等部前
            via: 遠藤
            sfc_direction: to
            stops:
              - name: 湘南台駅西口
                cumulative_time: 0
              - name: 円行上庭
                cumulative_time: 1
              - name: 北警察署前
                cumulative_time: 2
              - name: 工業団地入口
                cumulative_time: 4
              - name: 南大山
                cumulative_time: 5
              - name: 遠藤
                cumulative_time: 7
              - name: 藤沢ジャンボゴルフ前
                cumulative_time: 8
              - name: 慶応大学
                cumulative_time: 11
              - name: 慶応大学本館前
                cumulative_time: 12
              - name: 慶応中高等部前
                cumulative_time: 15
            csv_files:
              special_20250705: csv/special/20250705_sho23_to.csv
          sho23_from_rotary:
            name: 湘南台駅西口行
            origin: 慶応大学
            destination: 湘南台駅西口
            via: 遠藤
            sfc_direction: from
            stops:
              - name: 慶応大学
                cumulative_time: 0
              - name: 藤沢ジャンボゴルフ前
                cumulative_time: 1
              - name: 遠藤
                cumulative_time: 2
              - name: 南大山
                cumulative_time: 4
              - name: 工業団地入口
                cumulative_time: 5
              - name: 北警察署前
                cumulative_time: 6
              - name: 湘南台駅西口
                cumulative_time: 11
            csv_files:
              special_20250705: csv/special/20250705_sho23_from_rotary.csv
      sho25:
        name: 湘25
        paths:
          sho25_to:
            name: ツインライナー 急行・慶応大学行
            origin: 湘南台駅西口
            destination: 慶応中高等部前
            via: ツインライナー急行・南大山
            sfc_direction: to
            stops:
              - name: 湘南台駅西口
                cumulative_time: 0
              - name: 南大山
                cumulative_time: 5
              - name: 慶応大学
                cumulative_time: 9
              - name: 慶応大学本館前
                cumulative_time: 12
              - name: 慶応中高等部前
                cumulative_time: 15
            csv_files:
              special_20250705: csv/special/20250705_sho25_to.csv