name: Convert CSV to JSON

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        
    - name: Generate JSON files
      run: |
        python generate_json.py
        ls -la data/
        
    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Update gh-pages data using rsync
      run: |
        mkdir -p gh-pages/data
        rsync -av --delete data/ gh-pages/data/
        cp .nojekyll gh-pages/
        ls -la gh-pages/data/
        
    - name: Commit and push changes to gh-pages
      run: |
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # Force add generated JSON files to override .gitignore
        git add --force data/*.json
        git status
        if ! git diff --quiet || ! git diff --staged --quiet; then
          git commit -m "Update JSON files"
          git push
        else
          echo "No changes to commit"
        fi